### ISSUE TITLE
Disable Master password option

### ISSUE THREAD

**Issue by ArjitAgrawal** [alexandrecvieira/html-password-manager#9]
Hey there,

I liked your work. Just curious to know how can I enable or disable master password box?
Also, how to create separate tables with different headings?

Cheers.

**Comment by alexandrecvieira** [comment]
I did not understand your question, the master password is necessary to encrypt passwords, could you explain better what you would like to be implemented?

Thanks.
Cheers.

**Comment by alexandrecvieira** [comment]
Closed
